apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-converter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-converter
  template:
    metadata:
      labels:
        app: currency-converter
    spec:
      containers:
      - name: currency-converter
        image: currency-converter:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: currency-converter
spec:
  selector:
    app: currency-converter
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
